<a href="https://colab.research.google.com/github/dishankkalra23/NumPy-Tutorial/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Why studying numPy array? 
Python-list vs numPy-array**

1. List can have different data types while array have to store items of same data type.
2. List supports less datatypes than numPy.
3. numPy array is memory efficient and its speed is very fast because it is written in C






---

Importing library

In [1]:
import numpy as np
import string # Used in later cells



---


Creating a numpy array

In [ ]:
x = np.array([1,2,3,4,5])



---


type vs dtype 
* type: type of data structure like list,array,dictionary etc
* dtype: data type of data structure 

In [ ]:
print(type(x))
x.dtype

<class 'numpy.ndarray'>


dtype('int64')



---



Creating an array with specific data type

In [ ]:
z = np.array([10,20,32],dtype ='f')
print(z)

[10. 20. 32.]




---




Rank of array

In [ ]:
# 1D array:
[1,2,3,4,5]

# 2D array:
[[1,2,3],[4,5,6]]

# 3d array:
[[[1,2,3],[4,5,6]]]



---



1.   Shape: (number of rows,number of columns)
2.   Size: No. of rows * No. of columns

In [ ]:
y = np.array([[1,2,5],[3,4,5]])

print("Shape/Dimension:",y.shape)
print("Size: ",y.size)

Shape/Dimension: (2, 3)
Size:  6


3.   type
4.   dtype



In [ ]:
print("Type of data structure:",type(y))
print("Data type of array:",y.dtype)

Type of data structure: <class 'numpy.ndarray'>
Data type of array: int64




---




Saving numpy array in a file and loading it when it is needed

In [ ]:
arr_name = [1,2,3,4,5]
np.save('file_name',arr_name)

new_arr = np.load('file_name.npy')
print("Saved array:",new_arr)

Saved array: [1 2 3 4 5]




---




Upcasting in numpy: If the array contains elements of different datatypes then changing numPy automatically changes datatype to largest datatype in numpy.

**Upcast: integer --> float**

In [ ]:
a = np.array([1.2,3.4,4,5,6])
print(a)

[1.2 3.4 4.  5.  6. ]




---



Numpy array of lowercase alphabets and finding datatye, type, shape and size of array

In [ ]:
# import string
list_alphabet = list(string.ascii_lowercase)
alpha = np.array(list_alphabet)

print(alpha)
print(alpha.dtype)
print(type(alpha))
print(alpha.shape)
print(alpha.size)

['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'o' 'p' 'q' 'r'
 's' 't' 'u' 'v' 'w' 'x' 'y' 'z']
<U1
<class 'numpy.ndarray'>
(26,)
26




---



**Creating array using built-in functions**

full: Return a new array of given shape and type, filled with fill_value


*   full: np.full((3,2),fill_value)



In [ ]:
np.full((3,2),500)

array([[500, 500],
       [500, 500],
       [500, 500]])

In [ ]:
np.full((1,3),'hello')

array([['hello', 'hello', 'hello']], dtype='<U5')



---



zeros: Return a new array of given shape and type, filled with zeros.

*  np.zeros((shape_of_array))




In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.zeros((2,2),dtype='int32')

array([[0, 0],
       [0, 0]], dtype=int32)



---



ones: Return a new array of given shape and type, filled with ones

*  np.ones((shape_of_array))



In [ ]:
np.ones((2,1))

array([[1.],
       [1.]])

In [ ]:
np.ones((2,1),dtype = 'int32')

array([[1],
       [1]], dtype=int32)



---



eye: Return a 2-D array with ones on the diagonal and zeros elsewhere.

*   np.eye(no_of_rows,no_of_columns)

In [ ]:
np.eye(3,3,dtype='int32')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)



---



diag: Extract a diagonal or construct a diagonal array.

*   np.diag(list_of_values_on_main_diagonal,0)




In [ ]:
np.diag([10,-1,20,-1],0)

array([[10,  0,  0,  0],
       [ 0, -1,  0,  0],
       [ 0,  0, 20,  0],
       [ 0,  0,  0, -1]])



---



*   np.diag( list_of_values_on_diagonal, diagonal_above_main_diagonal)




In [ ]:
np.diag([10,-1,20,-1],1)

array([[ 0, 10,  0,  0,  0],
       [ 0,  0, -1,  0,  0],
       [ 0,  0,  0, 20,  0],
       [ 0,  0,  0,  0, -1],
       [ 0,  0,  0,  0,  0]])

In [ ]:
np.diag([10,-1,20,-1],2)

array([[ 0,  0, 10,  0,  0,  0],
       [ 0,  0,  0, -1,  0,  0],
       [ 0,  0,  0,  0, 20,  0],
       [ 0,  0,  0,  0,  0, -1],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0]])



---



 

*   np.diag(  list_of_values_on_diagonal, diagonal_below_main_diagonal)




In [ ]:
np.diag([10,-1,20],-1)

array([[ 0,  0,  0,  0],
       [10,  0,  0,  0],
       [ 0, -1,  0,  0],
       [ 0,  0, 20,  0]])

In [ ]:
np.diag([10,-1,20],-2)

array([[ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [10,  0,  0,  0,  0],
       [ 0, -1,  0,  0,  0],
       [ 0,  0, 20,  0,  0]])



---



arange: It creates an instance of ndarray with evenly spaced values and returns the reference to it.

*   arange: np.arange(start,stop,step) 
*   start is inclusive and stop is exclusive

In [ ]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = arr = np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])



---



linspace:Return evenly spaced numbers over a specified interval.

*   np.linspace(): np.linspace(start, stop, num=50, endpoint=True)
*   endpoint: Including end value



In [ ]:
np.linspace(5,50,10)

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [ ]:
np.linspace(5,50,10,endpoint=False)

array([ 5. ,  9.5, 14. , 18.5, 23. , 27.5, 32. , 36.5, 41. , 45.5])



---



random.random: Return random floats in the half-open interval [0.0, 1.0)

*   np.random.random(shape)


In [ ]:
np.random.random((3,2))

array([[0.32372433, 0.76357451],
       [0.4477029 , 0.94274949],
       [0.69158957, 0.52201261]])

In [ ]:
np.random.randint(-10,15)

7

In [ ]:
np.random.normal(15, 25, (5,3))

array([[ 22.04843455,  49.93344179,  15.84687413],
       [ 24.83829961,  13.97254251,  18.62530335],
       [  2.41594454,  52.97257162, -26.39507302],
       [ 33.66652382, -19.36906639, -21.90581423],
       [-23.1222272 ,  18.1077159 ,  -0.59926916]])



---



Accessing 2D Array

In [2]:
arr = np.random.random((5,5))
arr

array([[0.20354998, 0.25023229, 0.05100054, 0.47581847, 0.28033852],
       [0.97427847, 0.59159081, 0.57701749, 0.77632464, 0.36234029],
       [0.27945802, 0.86058357, 0.21515288, 0.14141807, 0.64832643],
       [0.90511932, 0.63271313, 0.56774632, 0.05519788, 0.75500518],
       [0.18195874, 0.88061743, 0.73577434, 0.70596383, 0.11307918]])

In [ ]:
arr[0][0]

0.4464959949362295

In [ ]:
arr[0,0]

0.4464959949362295



---



**Sorting numpy**

In [3]:
arr1 = np.random.random((2,2))
arr1

array([[0.83853036, 0.71190889],
       [0.88455665, 0.49839209]])



---




np.sort(a, axis=-1):
1.  Return a sorted copy of an array
2.  It doesn't sort the original array 



In [4]:
np.sort(arr1)

array([[0.71190889, 0.83853036],
       [0.49839209, 0.88455665]])

In [5]:
arr1

array([[0.83853036, 0.71190889],
       [0.88455665, 0.49839209]])



---



a.sort(axis=-1, kind=None, order=None):

1.   Sort an array in-place
2.   It sort the original array 



In [6]:
arr1.sort()

In [7]:
arr1

array([[0.71190889, 0.83853036],
       [0.49839209, 0.88455665]])



---



np.unique(array): Find the unique elements of an array

In [14]:
x = np.array([[1,2,2],[4,4,6]])
x

array([[1, 2, 2],
       [4, 4, 6]])

In [17]:
np.unique(x).reshape(2,2)

array([[1, 2],
       [4, 6]])

**Boolean Indexing**: Selecting values from array when we dont know the exact indices of values

In [ ]:
new_arr1 = x
new_arr1[(new_arr1 > 20)]

array([21, 22, 23, 24, 25])

In [ ]:
new_arr1[(new_arr1 > 5) & (new_arr1 < 11)]

array([ 6,  7,  8,  9, 10])

Accessing odd values using boolean indexing and changing their value to -100


In [ ]:
x[x%2!=0] = -100
x

array([-100,    2, -100,    4, -100,    6, -100,    8, -100,   10, -100,
         12, -100,   14, -100,   16, -100,   18, -100,   20, -100,   22,
       -100,   24, -100])