<a href="https://colab.research.google.com/github/dishankkalra23/NumPy-Tutorial/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Why studying numPy array? 
Python-list vs numPy-array**

1. List can have different data types while array have to store items of same data type.
2. List supports less datatypes than numPy.
3. numPy array is memory efficient and its speed is very fast because it is written in C






---

Importing library

In [2]:
import numpy as np
import string # Used in later cells



---


Creating a numpy array

In [4]:
x = np.array([1,2,3,4,5])



---


type vs dtype 
* type: type of data structure like list,array,dictionary etc
* dtype: data type of data structure 

In [5]:
print(type(x))
x.dtype

<class 'numpy.ndarray'>


dtype('int64')



---



Creating an array with specific data type

In [6]:
z = np.array([10,20,32],dtype ='f')
print(z)

[10. 20. 32.]




---




Rank of array: for example (x is 1/ 1d array)

In [ ]:
# 1D array:
[1,2,3,4,5]

# 2D array:
[[1,2,3],[4,5,6]]

# 3d array:
[[[1,2,3],[4,5,6]]]



---



1.   Shape: (number of rows,number of columns)
2.   Size: No. of rows * No. of columns

In [8]:
y = np.array([[1,2,5],[3,4,5]])

print("Shape/Dimension:",y.shape)
print("Size: ",y.size)

Shape/Dimension: (2, 3)
Size:  6


3.   type
4.   dtype



In [9]:
print("Type of data structure:",type(y))
print("Data type of array:",y.dtype)

Type of data structure: <class 'numpy.ndarray'>
Data type of array: int64




---




Saving numpy array in a file and loading it when it is needed

In [ ]:
arr_name = [1,2,3,4,5]
np.save('file_name',arr_name)

new_arr = np.load('file_name.npy')
print("Saved array:",new_arr)

Saved array: [1 2 3 4 5]




---




Upcasting in numpy: If the array contains elements of different data types and then changing data type to largest data type automatically in numpy.
Upcast: integer --> float

In [ ]:
a = np.array([1.2,3.4,4,5,6])
print(a)

[1.2 3.4 4.  5.  6. ]




---



Numpy array of lowercase alphabets and finding datatye, type, shape and size of array

In [10]:
# import string
list_alphabet = list(string.ascii_lowercase)
alpha = np.array(list_alphabet)

print(alpha)
print(alpha.dtype)
print(type(alpha))
print(alpha.shape)
print(alpha.size)

['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'o' 'p' 'q' 'r'
 's' 't' 'u' 'v' 'w' 'x' 'y' 'z']
<U1
<class 'numpy.ndarray'>
(26,)
26




---



arange: It creates an instance of ndarray with evenly spaced values and returns the reference to it.

In [21]:
x = np.arange(1,26)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

reshape: Gives a new shape to an array without changing its data.

In [22]:
x.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Boolean Indexing: Selecting values from array when we dont know the exact indices of values

In [26]:
new_arr1 = x
new_arr1[(new_arr1 > 20)]

array([21, 22, 23, 24, 25])

In [27]:
new_arr1[(new_arr1 > 5) & (new_arr1 < 11)]

array([ 6,  7,  8,  9, 10])

Accessing odd values using boolean indexing and changing their value to -100


In [28]:
x[x%2!=0] = -100
x

array([-100,    2, -100,    4, -100,    6, -100,    8, -100,   10, -100,
         12, -100,   14, -100,   16, -100,   18, -100,   20, -100,   22,
       -100,   24, -100])

random: Random values in a given shape.

In [ ]:
np.random.randint(1,10,size = (5,5))

array([[3, 9, 3, 8, 9],
       [1, 5, 7, 6, 5],
       [5, 9, 8, 9, 1],
       [5, 3, 9, 7, 6],
       [3, 9, 6, 5, 7]])

In [ ]:
x = np.ones((4,4))*np.array([1,2,3,4]).reshape(1,4)
x

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])